Web/SoccerSolutionsApp.Web/Controllers/FixturesController.cs
namespace SoccerSolutionsApp.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using SoccerSolutionsApp.Services.Data.Fixtures;
    using SoccerSolutionsApp.Services.Data.H2H;
    using SoccerSolutionsApp.Services.Data.Leagues;
    using SoccerSolutionsApp.Web.ViewModels.Fixtures;
    using SoccerSolutionsApp.Web.ViewModels.H2H;
    using SoccerSolutionsApp.Web.ViewModels.Main;
    using SoccerSolutionsApp.Web.ViewModels.Teams;

    public class FixturesController : Controller
    {
        private const int LeaguesPerPage = 25;
        private readonly IFixturesService fixturesService;
        private readonly ILeaguesService leaguesService;
        private readonly IH2HService h2HService;

        public FixturesController(
            IFixturesService fixturesService,
            ILeaguesService leaguesService,
            IH2HService h2HService)
        {
            this.fixturesService = fixturesService;
            this.leaguesService = leaguesService;
            this.h2HService = h2HService;
        }

        public IActionResult Add()
        {
            return View();
        }

        public async Task<IActionResult> ByDate(FixturesByDateInputModel model)
        {
            var viewModel = new FixturesByDateViewModel();

            viewModel.Leagues = this.leaguesService.GetAll<LeaguesListingViewModel>();

           

            foreach (var league in viewModel.Leagues)
            {
                league.NextFixturesForLeague = await this.fixturesService.GetFixtureForDate(league.Id, model.Date);
            }

            return this.View(viewModel);
        }

        public async Task<IActionResult> ById(int fixtureId)
        {
            var viewModel = await this.fixturesService.GetSingleFixtureById(fixtureId);

            if (viewModel == null)
            {
                return this.BadRequest();
            }

            //hardcode values -> im taking 8 past matches for each team plus 2 next matches for each team!

            viewModel.HomeTeamPastMatches = await this.fixturesService.GetPastFixturesForTeamByIdAsync(viewModel.HomeTeamId, 8);
            viewModel.HomeTeamNextMatches = await this.fixturesService.GetNexTFixturesForTeamByIdAsync(viewModel.HomeTeamId, 2);
            viewModel.AwayTeamPastMatches = await this.fixturesService.GetPastFixturesForTeamByIdAsync(viewModel.AwayTeamId, 8);
            viewModel.HomeTeamNextMatches = await this.fixturesService.GetNexTFixturesForTeamByIdAsync(viewModel.HomeTeamId, 2);

            return this.View(viewModel);
        }


        public async Task<IActionResult> Head2Head(int fixtureId, int hometeamId, int awayTeamId)
        {
            H2HViewModel viewModel = await this.h2HService.PrepareViewModel(hometeamId, awayTeamId);
            viewModel.TeamsDetails = await this.fixturesService.GetH2HTeamsInfo(fixtureId);
            viewModel.Fixtures = await this.fixturesService.GetHead2Head(hometeamId, awayTeamId);

            return this.View(viewModel);
        }
    }
}

Web/SoccerSolutionsApp.Web/Controllers/HomeController.cs
namespace SoccerSolutionsApp.Web.Controllers
{
    using System;
    using System.Collections;
    using System.Diagnostics;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using SoccerSolutionsApp.Data.Common.Repositories;
    using SoccerSolutionsApp.Data.Models;
    using SoccerSolutionsApp.Services.Data.Fixtures;
    using SoccerSolutionsApp.Services.Data.Leagues;
    using SoccerSolutionsApp.Web.ViewModels;
    using SoccerSolutionsApp.Web.ViewModels.Main;

    public class HomeController : Controller
    {
        private const int LeaguesPerPage = 25;
        private readonly ILeaguesService leaguesService;
        private readonly IFixturesService fixturesService;

        public HomeController(
            ILeaguesService leaguesService,
            IFixturesService fixturesService)
        {
            this.leaguesService = leaguesService;
            this.fixturesService = fixturesService;
        }

        public async Task<IActionResult> Index(int page = 1)
        {
            var viewModel = new MainPageLeaguesListingViewModel();
            viewModel.Leagues = this.leaguesService.GetAll<LeaguesListingViewModel>(LeaguesPerPage, (page - 1) * LeaguesPerPage);

            foreach (var model in viewModel.Leagues)
            {
                model.NextFixturesForLeague = await this.fixturesService.GetNextFixturesByLeagueIdAsync(model.Id);
            }

            int pages = await this.leaguesService.CountAsync();

            viewModel.PagesCount = (int)Math.Ceiling((double)pages / LeaguesPerPage);
            viewModel.CurrentPage = page;
            return this.View(viewModel);
        }

        public IActionResult Privacy()
        {
            return this.View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return this.View(
                new ErrorViewModel { RequestId = Activity.Current?.Id ?? this.HttpContext.TraceIdentifier });
        }

    }
}

Web/SoccerSolutionsApp.Web/Controllers/LeaguesController.cs
namespace SoccerSolutionsApp.Web.Controllers
{
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using SoccerSolutionsApp.Services.Data.Countries;
    using SoccerSolutionsApp.Services.Data.Fixtures;
    using SoccerSolutionsApp.Services.Data.Leagues;
    using SoccerSolutionsApp.Web.ViewModels.Competitions;
    using SoccerSolutionsApp.Web.ViewModels.Leagues;

    public class LeaguesController : Controller
    {
        private readonly ILeaguesService leaguesService;
        private readonly ICountriesService countriesService;
        private readonly IFixturesService fixturesService;

        public LeaguesController(
            ILeaguesService leaguesService,
            ICountriesService countriesService,
            IFixturesService fixturesService)
        {
            this.leaguesService = leaguesService;
            this.countriesService = countriesService;
            this.fixturesService = fixturesService;
        }


        public async Task<IActionResult> All()
        {
            var viewModel = new CountriesAndLeaguesListingViewModel();
            viewModel.Countries = this.countriesService.GetCountriesWithLeagues();

            foreach (var country in viewModel.Countries)
            {
                country.Leagues = await this.leaguesService.GetLeaguesByCountryId(country.Id);
            }

            return this.View(viewModel);
        }

        public async Task<IActionResult> ById(string countryName, int leagueId, string leagueName)
        {
            var viewModel = new LeaguesByCountryNameViewModel();

            int countryId = await this.countriesService.GetCountryIdByName(countryName);
            viewModel.CurrentLeagueId = leagueId;
            viewModel.CountryName = countryName;
            viewModel.CurrentLeagueName = leagueName;
            viewModel.Leagues = await this.leaguesService.GetLeaguesByCountryId(countryId);
            viewModel.Fixtures = await this.fixturesService.GetFixturesForLeagueId(leagueId);

            return this.View(viewModel);
        }
    }
}

Web/SoccerSolutionsApp.Web/Controllers/TeamsController.cs
namespace SoccerSolutionsApp.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using SoccerSolutionsApp.Services.Data.Countries;
    using SoccerSolutionsApp.Services.Data.Fixtures;
    using SoccerSolutionsApp.Services.Data.Leagues;
    using SoccerSolutionsApp.Services.Data.TeamsServices;
    using SoccerSolutionsApp.Web.ViewModels.Teams;

    public class TeamsController : Controller
    {
        private const int FixturesPerPage = 20;
        private const int NexFixturePerPage = 4;

        private readonly ITeamsService teamsService;
        private readonly ICountriesService countriesService;
        private readonly IFixturesService fixturesService;
        private readonly ILeaguesService leaguesService;

        public TeamsController(
            ITeamsService teamsService,
            ICountriesService countriesService,
            IFixturesService fixturesService,
            ILeaguesService leaguesService)
        {
            this.teamsService = teamsService;
            this.countriesService = countriesService;

            this.fixturesService = fixturesService;
            this.leaguesService = leaguesService;
        }

        public async Task<IActionResult> All()
        {
            var viewModel = await this.teamsService.GetAll<TeamListingViewModel>();
            return this.View(viewModel);
        }

        public async Task<IActionResult> ById(int teamId)
        {
            var teamViewModel = await this.teamsService.GetTeamByIdAsync<TeamInfoViewModel>(teamId);

            int pages = await this.fixturesService.CountPastFixturesAsync(teamId);

            teamViewModel.PagesCount = (int)Math.Ceiling((double)pages / FixturesPerPage);
            teamViewModel.CurrentPage = teamViewModel.PagesCount;

            teamViewModel.PastFixtures = await this.fixturesService.GetPastFixturesForTeamByIdAsync(teamId, FixturesPerPage - NexFixturePerPage, (teamViewModel.PagesCount - 1) * FixturesPerPage);
            teamViewModel.NextFixtures = await this.fixturesService.GetNexTFixturesForTeamByIdAsync(teamId, NexFixturePerPage);

            return this.View(teamViewModel);
        }

        public async Task<IActionResult> ListingGamesById(int teamId, int page)
        {
            var teamViewModel = await this.teamsService.GetTeamByIdAsync<TeamInfoViewModel>(teamId);

            int pages = await this.fixturesService.CountPastFixturesAsync(teamId);

            teamViewModel.PagesCount = (int)Math.Ceiling((double)pages / FixturesPerPage);
            teamViewModel.CurrentPage = page;

            teamViewModel.PastFixtures = await this.fixturesService.GetPastFixturesForTeamByIdAsync(teamId, FixturesPerPage - NexFixturePerPage, (page - 1) * FixturesPerPage);
            teamViewModel.NextFixtures = await this.fixturesService.GetNexTFixturesForTeamByIdAsync(teamId, NexFixturePerPage);

            return this.View("ById", teamViewModel);
        }

        public async Task<IActionResult> AllGames(int teamId, int page = 1)
        {
            var viewModel = await this.teamsService.GetTeamByIdAsync<TeamInfoViewModel>(teamId);

            int pages = await this.fixturesService.CountPastFixturesAsync(teamId);

            viewModel.PagesCount = (int)Math.Ceiling((double)pages / 40);
            viewModel.CurrentPage = page;

            viewModel.PastFixtures = await this.fixturesService.GetAllPastFixturesByTeamId(teamId, 40 - 10, (page - 1) * FixturesPerPage);
            viewModel.NextFixtures = await this.fixturesService.GetAllNextFixtures(teamId);
            viewModel.Leagues = await this.leaguesService.GetLeaguesForTeam(teamId);

            return this.View(viewModel);
        }

        public async Task<IActionResult> HomeGames(int teamId)
        {
            var viewModel = await this.teamsService.GetTeamByIdAsync<TeamInfoViewModel>(teamId);
            viewModel.PastFixtures = await this.fixturesService.GetAllPastWhereTeamIsHome(teamId);
            viewModel.Leagues = await this.leaguesService.GetLeaguesForTeam(teamId);

            return this.View("AllGames", viewModel);
        }

        public async Task<IActionResult> AwayGames(int teamId)
        {
            var viewModel = await this.teamsService.GetTeamByIdAsync<TeamInfoViewModel>(teamId);
            viewModel.PastFixtures = await this.fixturesService.GetAllPastWhereTeamIsAway(teamId);
            viewModel.Leagues = await this.leaguesService.GetLeaguesForTeam(teamId);

            return this.View("AllGames", viewModel);
        }

        public async Task<IActionResult> ByLeague(int teamId, int leagueId)
        {
            var viewModel = await this.teamsService.GetTeamByIdAsync<TeamInfoViewModel>(teamId);
            viewModel.PastFixtures = await this.fixturesService.GetAllPastForTeamAndLeague(teamId, leagueId);
            viewModel.Leagues = await this.leaguesService.GetLeaguesForTeam(teamId);

            return this.View("AllGames", viewModel);
        }
    }

}

Web/SoccerSolutionsApp.Web/Views/Home/Index.cshtml
@model SoccerSolutionsApp.Web.ViewModels.Main.MainPageLeaguesListingViewModel

@using SoccerSolutionsApp.Common;

@{
    this.ViewData["Title"] = "Home page";
}


<div class="">
    <div class="row">
        <div class="col-md-8 ">
            <nav>
                @if (Model.CurrentPage > 1)
                {
                    <a style="float:left; color:#000000; margin-top:5px;" asp-controller="Home" asp-action="Index" asp-route-page="@(Model.CurrentPage - 1)"><i class="fas fa-angle-double-left"></i> Previous</a>
                }
                @if (Model.CurrentPage < Model.PagesCount)
                {
                    <a style="float:right; color:#000000;" asp-controller="Home" asp-action="Index" asp-route-page="@(Model.CurrentPage + 1)">Next  <i class="fas fa-angle-double-right"></i></a>
                }
            </nav>
            <table class="table">
                @foreach (var league in Model.Leagues)
                {
                    <thead class="thead-dark" style="border-bottom-style: solid;">
                        <tr class="leaguesmain" style="cursor:pointer;" asp-controller="Leagues" asp-action="ById" asp-route-id="@league.Id" onclick="showFixtures(@league.Id)">
                            <th scope="row">
                                <i class="@league.CountryName.ToLower() flag"></i>
                                <span>@league.CountryName - @league.Name</span>
                                <a asp-controller="Leagues" asp-action="ById" asp-route-countryName="@league.CountryName" asp-route-leagueId="@league.Id" asp-route-leagueName="@league.Name"><i class="fas fa-arrow-alt-circle-right float-right" style="color:#ffffff"></i></a>
                                @*
                                *@
                            </th>
                        </tr>
                    </thead>
                    @if (league.NextFixturesForLeague != null)
                    {
                        <tbody>
                            @foreach (var fixtures in league.NextFixturesForLeague)
                            {
                                <tr class=" @league.Id row-cols-1" 
                                    style="display:none; border-bottom-style:groove; border-bottom-color: #f03d3d;">
                                    <th scope="col"></th>
                                    <td class="middle1" style="width:40%; text-align:right;">
                                    <a style="color: #212529;" asp-controller="Teams" asp-action="ById" asp-route-teamId="@fixtures.HomeTeamId">@fixtures.HomeTeamName</a>
                                    </td>
                                    
                                    <td class="middle" style="width:20%; text-align:center;" >
                                    <a style="color: #212529;" asp-controller="Fixtures" asp-action="ById" asp-route-fixtureId="@fixtures.Id">@fixtures.StatusShort.ToUpper()</a>
                                    </td>
                                    <td class="middle1" style="width:40%; text-align:left">
                                    <a style="color: #212529;" asp-controller="Teams" asp-action="ById" asp-route-teamId="@fixtures.AwayTeamId">@fixtures.AwayTeamName</a>
                                    </td>
                                </tr>
                            }
                        </tbody>
                    }


                }
            </table>
        </div>
        <br />
        <div>
            <partial name="_CalendarDataPicker.cshtml" model="new SoccerSolutionsApp.Web.ViewModels.Fixtures.FixturesByDateInputModel()" />
        </div>
    </div>
</div>

@section Scripts {
    <script>
        function showFixtures(id) {
            if ($('.' + id).css('display') === 'none') {

                $('.' + id).show();
                $('.' + id).css('display', 'block');

            }
            else {
                $('.' + id).hide();
                $('.' + id).css('display', 'none');
            }

        }
    </script>
}

Web/SoccerSolutionsApp.Web/Views/Home/_CalendarDataPicker.cshtml
@model SoccerSolutionsApp.Web.ViewModels.Fixtures.FixturesByDateInputModel;
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["TodayDate"] = DateTime.UtcNow.ToString("dd-mm-yyyy");
}



<h3>
    Select date
</h3>
<br />
<form action="GET">
    <input asp-for="Date" asp-controller="Fixtures" asp-action="ByName" value="@DateTime.Today.ToString("yyyy-MM-dd")" type="Date" id="datepicker" />
    <hr />
    <input type="submit" value="Search" class="btn btn-primary" asp-controller="Fixtures" asp-action="ByDate" />
</form>




<script>

    $(document).ready(
        $(function () {
            var currentDate = new Date();

            $('#datepicker1').datepicker({
                inline: true,
                showOtherMonths: true,
                dayNamesMin: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'],
                dateFormat: 'dd/mm/yy',
                setDate: currentDate
            });
        }))

    $.fn.datepicker.noConflict()
</script>