Web/SoccerSolutionsApp.Web/Controllers/LeaguesController.cs
namespace SoccerSolutionsApp.Web.Controllers
{
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using SoccerSolutionsApp.Services.Data.Countries;
    using SoccerSolutionsApp.Services.Data.Fixtures;
    using SoccerSolutionsApp.Services.Data.Leagues;
    using SoccerSolutionsApp.Web.ViewModels.Competitions;
    using SoccerSolutionsApp.Web.ViewModels.Leagues;

    public class LeaguesController : Controller
    {
        private readonly ILeaguesService leaguesService;
        private readonly ICountriesService countriesService;
        private readonly IFixturesService fixturesService;

        public LeaguesController(
            ILeaguesService leaguesService,
            ICountriesService countriesService,
            IFixturesService fixturesService)
        {
            this.leaguesService = leaguesService;
            this.countriesService = countriesService;
            this.fixturesService = fixturesService;
        }


        public async Task<IActionResult> All()
        {
            var viewModel = new CountriesAndLeaguesListingViewModel();
            viewModel.Countries = this.countriesService.GetCountriesWithLeagues();

            foreach (var country in viewModel.Countries)
            {
                country.Leagues = await this.leaguesService.GetLeaguesByCountryId(country.Id);
            }

            return this.View(viewModel);
        }

        public async Task<IActionResult> ById(string countryName, int leagueId, string leagueName)
        {
            var viewModel = new LeaguesByCountryNameViewModel();

            int countryId = await this.countriesService.GetCountryIdByName(countryName);
            viewModel.CurrentLeagueId = leagueId;
            viewModel.CountryName = countryName;
            viewModel.CurrentLeagueName = leagueName;
            viewModel.Leagues = await this.leaguesService.GetLeaguesByCountryId(countryId);
            viewModel.Fixtures = await this.fixturesService.GetFixturesForLeagueId(leagueId);

            return this.View(viewModel);
        }
    }
}

Web/SoccerSolutionsApp.Web/Controllers/PredictionsController.cs
namespace SoccerSolutionsApp.Web.Controllers
{
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using SoccerSolutionsApp.Data.Models;
    using SoccerSolutionsApp.Services.Data.Countries;
    using SoccerSolutionsApp.Services.Data.Fixtures;
    using SoccerSolutionsApp.Services.Data.Leagues;
    using SoccerSolutionsApp.Services.Data.Predictions;
    using SoccerSolutionsApp.Services.Data.Users;
    using SoccerSolutionsApp.Web.ViewModels.Predictions;
    using SoccerSolutionsApp.Web.ViewModels.Teams;

    public class PredictionsController : Controller
    {
        private readonly IPredictionsService predictionsService;
        private readonly ICountriesService countriesService;
        private readonly ILeaguesService leaguesService;
        private readonly IFixturesService fixturesService;
        private readonly IUsersService usersService;
        private readonly UserManager<ApplicationUser> userManager;

        public PredictionsController(
            UserManager<ApplicationUser> userManager,
            IPredictionsService predictionsService,
            ICountriesService countriesService,
            ILeaguesService leaguesService,
            IFixturesService fixturesService,
            IUsersService usersService)
        {
            this.predictionsService = predictionsService;
            this.countriesService = countriesService;
            this.leaguesService = leaguesService;
            this.fixturesService = fixturesService;
            this.usersService = usersService;
            this.userManager = userManager;
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            var countries = this.countriesService.GetAll<CountriesDropDownViewModel>();

            var viewModel = new CreatePredictionInputViewModel()
            {
                Countries = countries,
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreatePredictionInputViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction(nameof(this.All));
            }

            var userId = this.userManager.GetUserId(this.User);

            await this.predictionsService.CreateAsync(model, userId);

            return this.RedirectToAction(nameof(this.All));
        }

        public async Task<IActionResult> All()
        {
            var userId = this.userManager.GetUserId(this.User);

            var model = new PredictionsListingAndFollowingsViewModel()
            {
                Predictions = await this.predictionsService.GetAll<PredictionsListingViewModel>(),
            };

            if (userId == null)
            {
                model.CurrentUserFollowings = new HashSet<string>();
            }
            else
            {
                model.CurrentUserFollowings = await this.usersService.GetCurrentUserFollowingsAsync(userId);
            }

            return this.View(model);
        }

        [Authorize]
        public async Task<IActionResult> GetFollowingsPredictions()
        {
            var userId = this.userManager.GetUserId(this.User);

            var model = new PredictionsListingAndFollowingsViewModel()
            {
                Predictions = this.predictionsService.GetFollowingsPredictions(userId),
            };

            if (userId == null)
            {
                model.CurrentUserFollowings = new HashSet<string>();
            }
            else
            {
                model.CurrentUserFollowings = await this.usersService.GetCurrentUserFollowingsAsync(userId);
            }

            return this.View("All", model);
        }

        public async Task<IActionResult> ById(int id)
        {
            var viewModel = await this.predictionsService.GetPredictionById(id);

            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }
    }
}

Web/SoccerSolutionsApp.Web/Controllers/TeamsController.cs
namespace SoccerSolutionsApp.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;
    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Mvc;
    using SoccerSolutionsApp.Services.Data.Countries;
    using SoccerSolutionsApp.Services.Data.Fixtures;
    using SoccerSolutionsApp.Services.Data.Leagues;
    using SoccerSolutionsApp.Services.Data.TeamsServices;
    using SoccerSolutionsApp.Web.ViewModels.Teams;

    public class TeamsController : Controller
    {
        private const int FixturesPerPage = 20;
        private const int NexFixturePerPage = 4;

        private readonly ITeamsService teamsService;
        private readonly ICountriesService countriesService;
        private readonly IFixturesService fixturesService;
        private readonly ILeaguesService leaguesService;

        public TeamsController(
            ITeamsService teamsService,
            ICountriesService countriesService,
            IFixturesService fixturesService,
            ILeaguesService leaguesService)
        {
            this.teamsService = teamsService;
            this.countriesService = countriesService;

            this.fixturesService = fixturesService;
            this.leaguesService = leaguesService;
        }

        public async Task<IActionResult> All()
        {
            var viewModel = await this.teamsService.GetAll<TeamListingViewModel>();
            return this.View(viewModel);
        }

        public async Task<IActionResult> ById(int teamId)
        {
            var teamViewModel = await this.teamsService.GetTeamByIdAsync<TeamInfoViewModel>(teamId);

            int pages = await this.fixturesService.CountPastFixturesAsync(teamId);

            teamViewModel.PagesCount = (int)Math.Ceiling((double)pages / FixturesPerPage);
            teamViewModel.CurrentPage = teamViewModel.PagesCount;

            teamViewModel.PastFixtures = await this.fixturesService.GetPastFixturesForTeamByIdAsync(teamId, FixturesPerPage - NexFixturePerPage, (teamViewModel.PagesCount - 1) * FixturesPerPage);
            teamViewModel.NextFixtures = await this.fixturesService.GetNexTFixturesForTeamByIdAsync(teamId, NexFixturePerPage);

            return this.View(teamViewModel);
        }

        public async Task<IActionResult> ListingGamesById(int teamId, int page)
        {
            var teamViewModel = await this.teamsService.GetTeamByIdAsync<TeamInfoViewModel>(teamId);

            int pages = await this.fixturesService.CountPastFixturesAsync(teamId);

            teamViewModel.PagesCount = (int)Math.Ceiling((double)pages / FixturesPerPage);
            teamViewModel.CurrentPage = page;

            teamViewModel.PastFixtures = await this.fixturesService.GetPastFixturesForTeamByIdAsync(teamId, FixturesPerPage - NexFixturePerPage, (page - 1) * FixturesPerPage);
            teamViewModel.NextFixtures = await this.fixturesService.GetNexTFixturesForTeamByIdAsync(teamId, NexFixturePerPage);

            return this.View("ById", teamViewModel);
        }

        public async Task<IActionResult> AllGames(int teamId, int page = 1)
        {
            var viewModel = await this.teamsService.GetTeamByIdAsync<TeamInfoViewModel>(teamId);

            int pages = await this.fixturesService.CountPastFixturesAsync(teamId);

            viewModel.PagesCount = (int)Math.Ceiling((double)pages / 40);
            viewModel.CurrentPage = page;

            viewModel.PastFixtures = await this.fixturesService.GetAllPastFixturesByTeamId(teamId, 40 - 10, (page - 1) * FixturesPerPage);
            viewModel.NextFixtures = await this.fixturesService.GetAllNextFixtures(teamId);
            viewModel.Leagues = await this.leaguesService.GetLeaguesForTeam(teamId);

            return this.View(viewModel);
        }

        public async Task<IActionResult> HomeGames(int teamId)
        {
            var viewModel = await this.teamsService.GetTeamByIdAsync<TeamInfoViewModel>(teamId);
            viewModel.PastFixtures = await this.fixturesService.GetAllPastWhereTeamIsHome(teamId);
            viewModel.Leagues = await this.leaguesService.GetLeaguesForTeam(teamId);

            return this.View("AllGames", viewModel);
        }

        public async Task<IActionResult> AwayGames(int teamId)
        {
            var viewModel = await this.teamsService.GetTeamByIdAsync<TeamInfoViewModel>(teamId);
            viewModel.PastFixtures = await this.fixturesService.GetAllPastWhereTeamIsAway(teamId);
            viewModel.Leagues = await this.leaguesService.GetLeaguesForTeam(teamId);

            return this.View("AllGames", viewModel);
        }

        public async Task<IActionResult> ByLeague(int teamId, int leagueId)
        {
            var viewModel = await this.teamsService.GetTeamByIdAsync<TeamInfoViewModel>(teamId);
            viewModel.PastFixtures = await this.fixturesService.GetAllPastForTeamAndLeague(teamId, leagueId);
            viewModel.Leagues = await this.leaguesService.GetLeaguesForTeam(teamId);

            return this.View("AllGames", viewModel);
        }
    }

}

Web/SoccerSolutionsApp.Web/Views/Shared/_Layout.cshtml
@using SoccerSolutionsApp.Common
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <script src="~/lib/jquery/dist/jquery.js" asp-append-version="true"></script>
    <link href="~/css/bootstrap.min.css" rel="stylesheet" />
    <script src="~/lib/jquery-ui/jquery-ui.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js" asp-append-version="true"></script>
    <script src="~/lib/jquery-validation/dist/jquery.validate.js"></script>
    <script src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.js"></script>
    <link href="~/lib/jquery-ui/themes/le-frog/jquery-ui.css" rel="stylesheet" />
    <link href="~/lib/fontawesome/css/all.min.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/lib/bootstrap/dist/css/bootstrap.css" rel="stylesheet" asp-append-version="true" />
    <link href="~/css/bootstrap.css" rel="stylesheet" />
    <link href="~/css/customstyles.css" rel="stylesheet" />
    <link href="~/css/addons/flag.min.css" rel="stylesheet" />
    <link href="~/font-awesome/css/fontawesome.css" rel="stylesheet" />
    <link href="~/css/customstyles.css" rel="stylesheet" />


</head>

<body>
    <header>

        <nav class="navbar navbar-expand-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">@GlobalConstants.SystemName</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Fixtures</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Leagues" asp-action="All">Competitions</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Teams" asp-action="All">Teams</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Predictions" asp-action="All">Predictions</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @this.RenderBody()
        </main>

    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; @DateTime.Now.Year - @GlobalConstants.SystemName - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>


    @this.RenderSection("Scripts", required: false)
</body>
</html>