Web/SoccerSolutionsApp.Web/Areas/Identity/Controllers/UserController.cs
namespace SoccerSolutionsApp.Web.Areas.Identity.Controllers
{
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using SoccerSolutionsApp.Data.Models;
    using SoccerSolutionsApp.Services.Data.Predictions;
    using SoccerSolutionsApp.Services.Data.Users;
    using SoccerSolutionsApp.Web.ViewModels.User;

    [Area("Identity")]
    public class UserController : Controller
    {
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IPredictionsService predictionsService;
        private readonly IUsersService usersService;

        public UserController(
            UserManager<ApplicationUser> userManager,
            IPredictionsService predictionsService,
            IUsersService usersService)
        {
            this.userManager = userManager;
            this.predictionsService = predictionsService;
            this.usersService = usersService;
        }

        public async Task<IActionResult> ById(string userName)
        {
            var user = await this.userManager.FindByNameAsync(userName);

            var viewModel = new UserInfoViewModel
            {
                UserUsername = user.UserName,
                UserPredictions = await this.predictionsService.GetUserPredictions(user.Id),
            };

            return this.View(viewModel);
        }

        public async Task<IActionResult> AllUsers()
        {
            var viewModel = await this.usersService.GetAllUsersAsync();
            return this.View(viewModel);
        }

    }
}

Web/SoccerSolutionsApp.Web/Controllers/PredictionsController.cs
namespace SoccerSolutionsApp.Web.Controllers
{
    using System.Collections.Generic;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Authorization;
    using Microsoft.AspNetCore.Identity;
    using Microsoft.AspNetCore.Mvc;
    using SoccerSolutionsApp.Data.Models;
    using SoccerSolutionsApp.Services.Data.Countries;
    using SoccerSolutionsApp.Services.Data.Fixtures;
    using SoccerSolutionsApp.Services.Data.Leagues;
    using SoccerSolutionsApp.Services.Data.Predictions;
    using SoccerSolutionsApp.Services.Data.Users;
    using SoccerSolutionsApp.Web.ViewModels.Predictions;
    using SoccerSolutionsApp.Web.ViewModels.Teams;

    public class PredictionsController : Controller
    {
        private readonly IPredictionsService predictionsService;
        private readonly ICountriesService countriesService;
        private readonly ILeaguesService leaguesService;
        private readonly IFixturesService fixturesService;
        private readonly IUsersService usersService;
        private readonly UserManager<ApplicationUser> userManager;

        public PredictionsController(
            UserManager<ApplicationUser> userManager,
            IPredictionsService predictionsService,
            ICountriesService countriesService,
            ILeaguesService leaguesService,
            IFixturesService fixturesService,
            IUsersService usersService)
        {
            this.predictionsService = predictionsService;
            this.countriesService = countriesService;
            this.leaguesService = leaguesService;
            this.fixturesService = fixturesService;
            this.usersService = usersService;
            this.userManager = userManager;
        }

        [Authorize]
        [HttpGet]
        public IActionResult Create()
        {
            var countries = this.countriesService.GetAll<CountriesDropDownViewModel>();

            var viewModel = new CreatePredictionInputViewModel()
            {
                Countries = countries,
            };

            return this.View(viewModel);
        }

        [HttpPost]
        [Authorize]
        public async Task<IActionResult> Create(CreatePredictionInputViewModel model)
        {
            if (!this.ModelState.IsValid)
            {
                return this.RedirectToAction(nameof(this.All));
            }

            var userId = this.userManager.GetUserId(this.User);

            await this.predictionsService.CreateAsync(model, userId);

            return this.RedirectToAction(nameof(this.All));
        }

        public async Task<IActionResult> All()
        {
            var userId = this.userManager.GetUserId(this.User);

            var model = new PredictionsListingAndFollowingsViewModel()
            {
                Predictions = await this.predictionsService.GetAll<PredictionsListingViewModel>(),
            };

            if (userId == null)
            {
                model.CurrentUserFollowings = new HashSet<string>();
            }
            else
            {
                model.CurrentUserFollowings = await this.usersService.GetCurrentUserFollowingsAsync(userId);
            }

            return this.View(model);
        }

        [Authorize]
        public async Task<IActionResult> GetFollowingsPredictions()
        {
            var userId = this.userManager.GetUserId(this.User);

            var model = new PredictionsListingAndFollowingsViewModel()
            {
                Predictions = this.predictionsService.GetFollowingsPredictions(userId),
            };

            if (userId == null)
            {
                model.CurrentUserFollowings = new HashSet<string>();
            }
            else
            {
                model.CurrentUserFollowings = await this.usersService.GetCurrentUserFollowingsAsync(userId);
            }

            return this.View("All", model);
        }

        public async Task<IActionResult> ById(int id)
        {
            var viewModel = await this.predictionsService.GetPredictionById(id);

            if (viewModel == null)
            {
                return this.NotFound();
            }

            return this.View(viewModel);
        }
    }
}

Web/SoccerSolutionsApp.Web/Views/Predictions/All.cshtml
@model SoccerSolutionsApp.Web.ViewModels.Predictions.PredictionsListingAndFollowingsViewModel


@{

    ViewData["Title"] = "All";
}

<h1>All</h1>




<p>
    @if (this.User.Identity.IsAuthenticated)
    {
        <a asp-action="Create">Create New</a>
    }

    <a asp-controller="Predictions" asp-action="All" class="btn btn-warning">All</a>
    <a asp-controller="Predictions" asp-action="GetFollowingsPredictions" class="btn btn-warning">Your followings</a>
</p>

<div class="container">
    @foreach (var item in Model.Predictions)
    {
        <div class="container">

            <div class="navbar-light bg-light border">
                <a class="navbar-brand" href="#">@item.Title</a>
                @if (!Model.CurrentUserFollowings.Contains(item.UserUsername))
                {
                    <a class="float-right mr-1"><i id="@item.UserId" onclick="followUser('@item.UserId');" class="fas fa-user-check" style="color:#0026ff">follow</i></a>
                }
                else
                {
                    <a class="float-right mr-1"><i id="@item.UserId" class="fas fa-check-double" style="color:#3fbe08"></i></a>
                }
                <a class="float-right mr-1" asp-area="Identity" asp-controller="User" asp-action="ById" asp-route-userName="@item.UserUsername" style="color:#000000">by @item.UserUsername  </a>
            </div>
            <div class="media mt-1 ">
                <figure>
                    <img class="mr-3" src="@item.FixtureHomeTeamLogo" alt="@item.FixtureHomeTeamName">
                    <figcaption class="figure-caption text-center" style="color:black">@item.FixtureHomeTeamName</figcaption>
                </figure>
                <figure>
                    <img class="mr-3" src="@item.FixtureAwayTeamLogo" alt="@item.FixtureAwayTeamName">
                    <figcaption class="figure-caption text-center" style="color:black">@item.FixtureAwayTeamName</figcaption>
                </figure>
                <div class="media-body text-break">
                    @Html.Raw(item.ShortContent) <a asp-action="ById" asp-route-id="@item.Id" class="btn btn-warning">Read More</a>
                </div>
                <div class="media-body">
                    <p style="margin-bottom:0; float:right;">Prediction:</p>
                    <br />
                    <p style="margin-top:0; float:right;">@item.GamePrediction</p>
                </div>
            </div>
            <hr />
        </div>
    }

</div>

<script>
    function followUser(userToFollowId) {

        $.ajax({
            url: `/Followings/FollowUser/`,
            type: "POST",
            data: {
                'userToFollowId': `${userToFollowId}`
            },


            success: function () {

                let line = "<i onclick=\"unfollowUser('@@item.UserId')\" class=\"fas fa-check-double\" \"style=color:#0026ff>unfollow</i>\";"
                $("#follow").html(line);
                $("#follow").attr("id", "unfollow");
            }

        });
    }

   
</script>

Web/SoccerSolutionsApp.Web/Views/Predictions/ById.cshtml
@model SoccerSolutionsApp.Web.ViewModels.Predictions.PredictionsListingViewModel


<div class="container">
    <div>
        <h5 style="color:#f03d3d">Prediction 
        <a class="float-right" asp-area="Identity" asp-controller="User" asp-action="ById" asp-route-userName="@Model.UserUsername"><strong>by @Model.UserUsername</strong></a></h5>
        
    </div>
    <div class="d-block border-top border-dark" style="background-color:#ede9e9">
        <div class="row clearfix">
            <div class="col container float-left position-relative">
                <h4>@Model.FixtureHomeTeamName</h4>
            </div>
            <div class="col container float-right position-relative">
                <h4><a class="float-right"> @Model.FixtureAwayTeamName</a></h4>
            </div>
        </div>
        <div class="row clearfix">
            <div class="col container float-left">
                <div>
                    <img src="@Model.FixtureHomeTeamLogo" alt="..." class="img-thumbnail rounded border-success">
                </div>
            </div>
            <div class="col container">
                <div class="">
                    <table>
                        <thead></thead>
                        <tbody>
                            <tr>
                                <td>
                                    @Html.Raw(Model.Content)
                                <td>
                            </tr>
                    </table>
                </div>
            </div>
            <div class="col container float-right">
                <div>
                    <img src="@Model.FixtureAwayTeamLogo" alt="..." class="img-thumbnail rounded border-success float-right">
                </div>
            </div>
        </div>
    </div>
</div>

Web/SoccerSolutionsApp.Web/Views/Predictions/Create.cshtml
@model SoccerSolutionsApp.Web.ViewModels.Predictions.CreatePredictionInputViewModel

@{
    var countries = Model.Countries.Select(x => new SelectListItem(x.Name, x.Id.ToString()));
}

<h1>Create prediction</h1>

<h4></h4>
<hr />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="All" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="CountryId">Country</label>
                <select asp-for="CountryId" asp-items="@countries" id="countryList" class="form-control btn btn-secondary dropdown-toggle">
                    <option>--Select Country--</option>
                </select>
                <span asp-validation-for="CountryId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LeagueId">League </label>
                <select asp-for="LeagueId" id="leagueId" class="selectpicker form-control btn btn-secondary dropdown-toggle">
                    <option>--Select League--</option>
                </select>
                <span asp-validation-for="LeagueId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FixtureId">Fixtures</label>
                <select asp-for="FixtureId"id="fixturesId" class="selectpicker form-control btn btn-secondary dropdown-toggle">
                    <option>--Select Event--</option>
                </select>
                <span asp-validation-for="FixtureId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Content" class="control-label">Content</label>
                <textarea asp-for="Content" class="form-control"></textarea>
                <span asp-validation-for="Content" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Prediction" class="control-label">Prediction</label>
                <select asp-for="Prediction" asp-vali class="selectpicker form-control btn btn-secondary dropdown-toggle">
                    <option>--Choose Prediction--</option>
                    <option>1</option>
                    <option>2</option>
                    <option>Over 2.5</option>
                    <option>Under 2.5</option>
                    <option>Both Teams To Score</option>
                    <option>Both Teams Not To Score</option>
                    <option>1X</option>
                    <option>2X</option>
                    <option>12</option>
                </select>
                <span asp-validation-for="Prediction" class="text-danger"></span>
            </div>
            <hr />
            <input type="submit" value="Create" class="btn btn-secondary dropdown-toggle" />
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    <script type="text/javascript">
        //Insert default item "Select" in dropdownlist on load
        $(document).ready(function () {
            var items = "<option value='0'>--Select League--</option>";
            $("#leagueId").html(items);
        });

        //Bind League dropdownlist
        $("#countryList").change(function () {
            var countryId = $("#countryList").val();
            var url = "/api/data/getleagues";


            $.getJSON(url, { countryId: countryId }, function (data) {
                var item = "";
                $("#leagueId").empty();
                item += "<option value='0'>--Select League--</option>"
                $.each(data, function (i, league) {
                    item += '<option value="' + league.value + '">' + league.text + '</option>'
                });
                $("#leagueId").html(item);
            })
        });

        $("#leagueId").change(function () {
            var leagueId = $("#leagueId").val();
            var url = "/api/data/getfixtures";

            $.getJSON(url, { leagueId: leagueId }, function (data) {
                console.log(data)
                var item = "";
                $("#fixturesId").empty();
                console.log(data);
                $.each(data, function (i, f) {
                    item += '<option value="' + f.value + '">' + f.text + '</option>'
                });
                $("#fixturesId").html(item);
            });
        });


    </script>

   
}